version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-stretch
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo pip install requests

      - run:
          name: run tests
          command: |
            python tests.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
